services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - monitoring-microservice

  church-db:
    image: postgres:13
    container_name: church-db
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: church_db
    ports:
      - "5430:5432"  # Change host port to 3308 or any other available port
    # volumes:
      # - auth-db-data:/var/lib/postgresql/data  # Referencing auth-db-data volume
      # - ./dbconfig/custom_pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf  # Mount your custom pg_hba.conf
      # - ./dbconfig/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql  # Mount the SQL initialization script
    networks:
      - monitoring-microservice

  auth-service:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    container_name: auth-service
    volumes:
      - ./apps/auth:/usr/src/app/apps/auth  # Only mount the auth service code if you are focusing on it
      - ./libs/common:/usr/src/app/libs/common
      - /usr/src/app/node_modules  # Prevents mounting node_modules, so Docker can use its own node_modules
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq
    environment:
      - NODE_PATH=./dist
      - RABBITMQ_URL=${RABBITMQ_SERVER}
      - CHOKIDAR_USEPOLLING=true
    command: >
      bash -c "node -v && npm run start:auth"
    networks:
      - monitoring-microservice

  church-service:
    build:
      context: .
      dockerfile: ./apps/church/Dockerfile
    container_name: church-service
    volumes:
      - ./apps/church:/usr/src/app/apps/church  # Mount the church service code
      - ./libs/common:/usr/src/app/libs/common
      - /usr/src/app/node_modules  # Prevents mounting node_modules, so Docker can use its own node_modules
    ports:
      - "3002:3002"
    depends_on:
      - rabbitmq
      - church-db
    environment:
      - NODE_PATH=./dist
      - DATABASE_URL=postgres://auth_user:auth_password@church-db:5432/church_db
      - POSTGRES_USER=auth_user
      - POSTGRES_PASSWORD=auth_password
      - POSTGRES_DB=church_db
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=church-db
      - RABBITMQ_URL=${RABBITMQ_SERVER}
      - CHOKIDAR_USEPOLLING=true
    command: >
      bash -c "node -v && npm run start:church"
    networks:
      - monitoring-microservice


  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    container_name: api-gateway
    volumes:
      - ./apps/api-gateway:/usr/src/app/apps/api-gateway  # Only mount the auth service code if you are focusing on it
      - ./libs/common:/usr/src/app/libs/common
      - /usr/src/app/node_modules  # Prevents mounting node_modules, so Docker can use its own node_modules
    ports:
      - "3000:3000"
    depends_on:
      - church-service
      - auth-service
      - rabbitmq
    environment:
      - NODE_PATH=./dist
      - RABBITMQ_URL=${RABBITMQ_SERVER}
      - CHOKIDAR_USEPOLLING=true
    command: >
      bash -c "node -v && npm run start:gateway"
    networks:
      - monitoring-microservice

networks:
  monitoring-microservice:
    driver: bridge

volumes:
  auth-db-data:  # Explicitly defining the volume for auth-db