name: Deploy to Cloudflare Pages

on:
  pull_request:
    types: [closed]
    branches:
      - master  # Replace with your default branch, e.g., main or master
      - IMP-DEPLOYMENT-CLOUDFLARE-SCRIPT
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build Project Prod
        if: github.base_ref == 'master'
        run: npm run build -- -c=production

      - name: Build Project Staging
        if: github.base_ref == 'staging'
        run: npm run build -- -c=staging  

      - name: Build Project IMP-DEPLOYMENT-CLOUDFLARE-SCRIPT
        if: github.base_ref == 'IMP-DEPLOYMENT-CLOUDFLARE-SCRIPT'
        run: npm run build -- -c=staging    

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CF_PROJECT_NAME }}  # Replace with your Cloudflare Pages project name
          directory: './dist/acps-conference/browser'  # Replace with your Angular project's dist folder
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}



# apiTOKEN = B7aRMzhIySQ-az4GIzO1U9yNwwtUcv3Dt2YfF_QR